spring:
  profiles:
    default: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: nekogasuk2@gmail.com
    password: qlls ewsr duvo cnhs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: S3cr3tK3yasdfasvlhasklrqklwefhlaskdfhlaksdfhlaskrhlkqewrhklfasdvnkansdk
  expiration: 86400000 # 1일
  refresh-token:
    expiration: 604800000 # 7일
file:
  upload_dir: C:/Users/asus/spring-study/lossion/upload/
aes:
  secret-key: AES_PRIVATE_KEY_THIS_TEST_32BYTE
  iv: 0987654321654321
