cloud:
  aws:
    s3:
      bucket: ENC(CqBvVeuf1ViKqrEhdDgz6g==)
    credentials:
      access-key: ENC(HBSuhCngM0K9HufzHk2TFxIRrEioYKv1hdYfLIvEddU=)
      secret-key: ENC(YAv+Mxhz/Exg/ni8FQfrQ/7Fcfx/aLtQtdojC4QK/Lt3SnYGsecSn6erI6cqYAiQNJFhGrVe+E4=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
