spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(+zIPZQ6bduQGKKme8YnmPY3kIQHM+JIbgsMsMvJT525nGtnpNQdvUm92XKW4e+8T6WJ5opeKdsEXKZqUVyGGF5BcyYWt3/ySoeigstm1gjK/gTrPklsBiiK428DgzzEctOvbD5GS4xbbt3znYJF8Ow33PP9zwWNlhQOU1HhCIWWHKyz6cJF7GA==)
    username: ENC(/s06/EW6cBrPllY5Fjvalg==)
    password: ENC(QfBTIjo/odzNvaAyFibBBdorrpjlgAyi)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect