name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: github-actions

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -Pjasypt.encryptor.password=${{ secrets.JASYPT_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
          # build Cache 적용
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cd-pipelines:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: lossion
          environment_name: LossionApp-env
          version_label: ${{ github.sha }}
          version_description: ${{ github.event.head_commit.message }}
          use_existing_version_if_available: true
          region: ${{ secrets.AWS_REGION }}
          deployment_package: docker-compose.yml